name: Cross - Release Binaries

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  cross-linux:
    name: Cross - ${{ matrix.target }}
    runs-on: ubuntu-24.04
    timeout-minutes: 45
    env:
      CARGO_INCREMENTAL: 0
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          -l
          - armv7-unknown-linux-gnueabihf
          - armv7-unknown-linux-musleabihf
          - arm-unknown-linux-gnueabi
          - arm-unknown-linux-musleabi
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        name: Cache Cargo registry + index
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: |
          rustup target add ${{ matrix.target }}
          cargo install cross --version 0.2.4 --force --locked
      - run: make cross-build-${{ matrix.target }}-release  # Build Release
      - uses: actions/upload-artifact@v4
        with:
          name: "vector-release-${{ matrix.target }}"
          path: "./target/${{ matrix.target }}/release/vector"
      - name: Rename binary and upload for release
        run: |
          mkdir -p release-binaries
          mv "./target/${{ matrix.target }}/release/vector" "release-binaries/vector-${{ matrix.target }}"
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release-binaries/vector-${{ matrix.target }}
          asset_name: vector-${{ matrix.target }}
          asset_content_type: application/octet-stream
